import Image from 'next/image'

/**
 * The wordmark.
 *
 * Two files rather than one, because the source logo is transparent-backed and its middle
 * ("he") and tagline are dark indigo — on the dark theme's near-black background those
 * disappear and the mark reads "FP LP". `logo-dark.png` lightens exactly those parts and
 * leaves the cyan-to-purple gradient alone. Both are generated by
 * `scripts/build-logo-assets.mts` from `assets/logo_original.png`.
 *
 * Swapped with CSS rather than by reading the theme in JS: the choice has to be right in
 * the server-rendered HTML, and a component that resolved it on the client would flash the
 * wrong one on first paint.
 */
export function Logo({
  width = 160,
  priority = false,
  className = '',
}: {
  width?: number
  /** Set on the landing and sign-in heroes, where the mark is the largest thing above the fold. */
  priority?: boolean
  className?: string
}) {
  /**
   * 1034x310 — the wordmark as `build-logo-assets.mts` writes it, tagline cropped off.
   * Kept in step by hand, so the script prints the ratio when it runs.
   */
  const height = Math.round((width * 310) / 1034)

  return (
    <>
      <Image
        src="/logo.png"
        alt="FPheLp - manage your fantasy league"
        width={width}
        height={height}
        priority={priority}
        className={`dark:hidden ${className}`}
      />
      <Image
        src="/logo-dark.png"
        alt="FPheLp - manage your fantasy league"
        width={width}
        height={height}
        priority={priority}
        aria-hidden
        className={`hidden dark:block ${className}`}
      />
    </>
  )
}
